### ISSUE TITLE
DHCP won't work!

### ISSUE THREAD

**Issue by H3wastooshort** [hrvach/espple#7]
Log:
`
add if0
f 0, scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
add 1
pm open phy_2,type:2 0 0
cnt

connected with FRITZBoxKarin, channel 11
dhcp client start...`
and here it ends!
No more Output!
Not listet in Router Interface!!

**Comment by hrvach** [comment]
Hello,

Does your wifi router have 802.11b enabled or it's set up as g only? 

Regards,

Hrvoje

**Comment by H3wastooshort** [comment]
g/n only

**Comment by hrvach** [comment]
Please try enabling 802.11b and try again. I've found claims it has better range with 802.11b only and decided to go that route. Sorry for the inconvenience!

Regards,

Hrvoje

**Comment by H3wastooshort** [comment]
No problem! But think of putting IT in the readme
