### ISSUE TITLE
binary with NTSC as the default?

### ISSUE THREAD

**Issue by inversephase** [hrvach/espple#8]
Sorry if this isn't a terribly appropriate place to do this:

I appreciate the option for NTSC output, but is there any possibility we can get a binary with NTSC as the default video output, for people that don't have the ESP toolchain or are having trouble getting the environment set up?

**Comment by hrvach** [comment]
Please try this and be so kind to tell me if it works for you. I don't have a NTSC TV to test at the moment, and if it works I'll make it available as download in the main repo...

[image.tar.gz](https://github.com/hrvach/espple/files/3250427/image.tar.gz)

Have fun! :+1:

**Comment by inversephase** [comment]
the image flashed and installed okay, and I just realised my TV is in an inaccessible place. I will be able to access it and fully test in the morning. thank you very much!

**Comment by hrvach** [comment]
Sure thing, hope it will work for you and I'll appreciate the feedback!

**Comment by inversephase** [comment]
Sorry it took so long, we have confirmed the NTSC binary as working! for some reason, the channel it works best on is 32 - but because of the spread you can also view it on several other channels.

**Comment by hrvach** [comment]
That's great to hear, I will be providing the binaries to others so they don't have to recompile. Thanks for the feedback!
